name: Master
on:
  push:
    branches:
      - master

jobs:
  # publish to gh-pages (& IPFS when a release is detected)
  www:
    name: build:www
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build:www
      run: |
        yarn install --immutable
        yarn build:www
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: packages/apps/build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
